spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_best_api?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: haneul
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: testsetestsetsetsetsetst!!!
  expire-time: 9999999

open-api:
  base-url: ${OPEN_API_BASE_URL}
  service-id: ${OPEN_API_SERVICE_ID}
  key: ${OPEN_API_KEY}
