spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: ${JWT_SECRET_KEY}
  expire-time: ${JWT_EXPIRED_TIME}

open-api:
  base-url: ${OPEN_API_BASE_URL}
  service-id: ${OPEN_API_SERVICE_ID}
  key: ${OPEN_API_KEY}
