spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_best_api?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: haneul
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: testsetestsetsetsetsetst!!!
  expire-time: 9999999