spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine=innodb: innodb
        format_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expire-time: ${JWT_EXPIRED_TIME}

open-api:
  base-url: ${OPEN_API_BASE_URL}
  service-id: ${OPEN_API_SERVICE_ID}
  key: ${OPEN_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
